env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  semi: [2, always]
  react/react-in-jsx-scope: off
